# https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=inmemory

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    #command: npm start
    volumes:
      - ./FUC-ftp-server:/usr/src/app
      #- ./FUC-ftp-server/tmp-output:/usr/src/app/tmp-output
      #- ./FUC-ftp-server/tmp-input:/usr/src/app/tmp-input
    ports:
      - "80:443"
    #depends_on:
    #  - mytb
    env_file:
      - ./FUC-ftp-server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mytb:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
      - "5432:5432"
    environment:
      TB_QUEUE_TYPE: in-memory
      SECURITY_USER_LOGIN_CASE_SENSITIVE: false

    user: "postgres"  # Run container as postgres user
    #command: bash -c "chown -R postgres:postgres /data/db && chmod -R 0700 /data/db && /usr/lib/postgresql/12/bin/postgres -D /data/db"

    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
      - ~/.mytb-config:/config

      - ./postgres-lock:/var/run/postgresql

      #- ./config-postgres/:/data/db/

      #- ./config/pg_hba.conf:/etc/postgresql/12/main/pg_hba.conf
      #- ./config/postgresql.conf:/etc/postgresql/12/main/postgresql.conf
      

volumes:
  postgres-config:
    driver: local