# https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=inmemory

services:

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # command: npm start
    volumes:
      - ./FUC-ftp-server:/usr/src/app
      #- ./FUC-ftp-server/tmp-output:/usr/src/app/tmp-output
      #- ./FUC-ftp-server/tmp-input:/usr/src/app/tmp-input
    ports:
      - "80:80" # Change to 80:443 if using SSL
    depends_on:
      - thingsboard
    env_file:
      - ./FUC-ftp-server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # https://hub.docker.com/r/prodrigestivill/postgres-backup-local
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres 
    volumes:
        - ~/.fuk-backups:/backups
    #links:
    #    - thingsboard:POSTGRES_HOST # :${POSTGRES_HOST}
    depends_on:
        - thingsboard
    environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - SCHEDULE=@daily
        - BACKUP_ON_START=TRUE
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080

  thingsboard:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090" # Change to 443:9090 if using SSL
      #- "1883:1883"
      #- "7070:7070"
      #- "5683-5688:5683-5688/udp"
      - "5432:5432"
    environment:
      TB_QUEUE_TYPE: in-memory
      # HTTP_BIND_PORT: 8080
      SECURITY_USER_LOGIN_CASE_SENSITIVE: false
      SSL_ENABLED: false
      SSL_CREDENTIALS_TYPE: PEM
      SSL_PEM_CERT: /centificates/fullchain.pem
      SSL_PEM_KEY: /centificates/privkey.pem
    volumes:
      - ~/.fuk-data:/data
      - ~/.fuk-logs:/var/log/thingsboard