# https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=inmemory

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    #command: npm start
    volumes:
      - ./FUC-ftp-server:/usr/src/app
      #- ./FUC-ftp-server/tmp-output:/usr/src/app/tmp-output
      #- ./FUC-ftp-server/tmp-input:/usr/src/app/tmp-input
    ports:
      - "80:443"
    #depends_on:
    #  - mytb
    env_file:
      - ./FUC-ftp-server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mytb:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    ports:
      - "443:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      # HTTP_BIND_PORT: 8080
      SECURITY_USER_LOGIN_CASE_SENSITIVE: false
      SSL_ENABLED: true
      SSL_CREDENTIALS_TYPE: PEM
      SSL_PEM_CERT: /config/fullchain.pem
      SSL_PEM_KEY: /config/privkey.pem
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
      # - ./etc/letsencrypt/live/thingsboard.gruenecho.de/fullchain.pem:/config/fullchain.pem
      # - ./etc/letsencrypt/live/thingsboard.gruenecho.de/privkey.pem:/config/privkey.pem
      - ~/.mytb-config:/config
